### PR TITLE
[DO NOT MERGE][v8.1] Test a patch

### PR DESCRIPTION
**Pull request by leofang**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
Hi @pauldmccarthy, this is for testing the segfault (#37) with pyobjc-core v8.1 + Mac OS X 10.14. Any chance you could run a quick check for me for the x86-64 build please? 

The artifact can be downloaded here:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=445971&view=artifacts&pathAsName=false&type=publishedArtifacts
Once you extract the zip file, there should be an osx-64 folder containing the package (with file extension .tar.bz2). Create a fresh conda env with the correct Python version matching the dowloaded package and then do
```
conda install /path/to/pyobjc-core.....tar.bz2
```
to install the package. Then, install `pyobjc-framework-cocoa` from conda-forge and test.

**Comment by pauldmccarthy** [comment]
Hi @leofang apologies for the delay. I'm afraid that this build triggered segfaults on both 10.14 and 10.15 :( Happy to run any further tests you might need.

**Comment by pauldmccarthy** [comment]
@leofang After going through my last comment, I realised that `conda install -y -c conda-forge -p ./test.env pyobjc-framework-cocoa` resulted in `pyobjc-framework-cocoa=6.2` being installed. Something in the recipe must have changed such that this build of `pyobjc-core` is incompatible with `pyobjc-framework-cocoa=8.2`, as I get conflict errors when I try to `conda install -y -c conda-forge -p ./test.env pyobjc-framework-cocoa=8.2`..

**Comment by leofang** [comment]
Thanks, @pauldmccarthy! To sum up:
- core 8.1 (from this PR) + cocoa 8.1 (from conda-forge): segfault
- core 8.2 + cocoa 8.2 (both from conda-forge): unknown 

Am I correct? If so, can we give 8.2 another shot? 🙂

The possibility of having core 8.2 + cocoa 6.2 is strange. We version-lock them tightly to avoid potential issues. Glad you noticed it.

**Comment by pauldmccarthy** [comment]
Hi @leofang, _core 8.2 + cocoa 8.2 (both from conda-forge)_ - yes, this does seem to work on 10.14 (and 10.15) - (just running `python -c "import CoreFoundation"`).

**Comment by leofang** [comment]
> Hi @leofang, _core 8.2 + cocoa 8.2 (both from conda-forge)_ - yes, this does seem to work on 10.14 (and 10.15) - (just running `python -c "import CoreFoundation"`).

Thank you, @pauldmccarthy! I guess it's best for you to move to 8.2, then. I wouldn't expect this PR to make any difference as the net effect should be identical, but I wasn't 100% confident. Instead, v8.2's changelog indicates that it has better support for various macOS versions:
> #317: Cleanup code dealing with libffi closures APIs on various versions of macOS

which I think should be why it works now.

**Pull request closed without merging**
